# CMake generated Testfile for 
# Source directory: E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER
# Build directory: E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[universal_autopilot_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Debug/universal_autopilot_adapter_contract_test.exe")
  set_tests_properties([=[universal_autopilot_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;25;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[universal_autopilot_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Release/universal_autopilot_adapter_contract_test.exe")
  set_tests_properties([=[universal_autopilot_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;25;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[universal_autopilot_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/MinSizeRel/universal_autopilot_adapter_contract_test.exe")
  set_tests_properties([=[universal_autopilot_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;25;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[universal_autopilot_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/RelWithDebInfo/universal_autopilot_adapter_contract_test.exe")
  set_tests_properties([=[universal_autopilot_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;25;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
else()
  add_test([=[universal_autopilot_adapter_contract_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[universal_equipment_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Debug/universal_equipment_adapter_contract_test.exe")
  set_tests_properties([=[universal_equipment_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;38;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[universal_equipment_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Release/universal_equipment_adapter_contract_test.exe")
  set_tests_properties([=[universal_equipment_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;38;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[universal_equipment_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/MinSizeRel/universal_equipment_adapter_contract_test.exe")
  set_tests_properties([=[universal_equipment_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;38;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[universal_equipment_adapter_contract_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/RelWithDebInfo/universal_equipment_adapter_contract_test.exe")
  set_tests_properties([=[universal_equipment_adapter_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;38;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
else()
  add_test([=[universal_equipment_adapter_contract_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[flight_evidence_recorder_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Debug/flight_evidence_recorder_test.exe")
  set_tests_properties([=[flight_evidence_recorder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;51;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[flight_evidence_recorder_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Release/flight_evidence_recorder_test.exe")
  set_tests_properties([=[flight_evidence_recorder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;51;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[flight_evidence_recorder_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/MinSizeRel/flight_evidence_recorder_test.exe")
  set_tests_properties([=[flight_evidence_recorder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;51;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[flight_evidence_recorder_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/RelWithDebInfo/flight_evidence_recorder_test.exe")
  set_tests_properties([=[flight_evidence_recorder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;51;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
else()
  add_test([=[flight_evidence_recorder_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[evidence_source_adapter_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Debug/evidence_source_adapter_test.exe")
  set_tests_properties([=[evidence_source_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;64;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[evidence_source_adapter_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/Release/evidence_source_adapter_test.exe")
  set_tests_properties([=[evidence_source_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;64;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[evidence_source_adapter_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/MinSizeRel/evidence_source_adapter_test.exe")
  set_tests_properties([=[evidence_source_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;64;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[evidence_source_adapter_test]=] "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/build_clean/RelWithDebInfo/evidence_source_adapter_test.exe")
  set_tests_properties([=[evidence_source_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;64;add_test;E:/Flight Planning/PROJECT_KNOWLEDGE/BlueSkyPro/04_SOFTWARE/AUTOPILOT_ADAPTER/CMakeLists.txt;0;")
else()
  add_test([=[evidence_source_adapter_test]=] NOT_AVAILABLE)
endif()
